services:
  - type: web
    name: brand-analysis-suite
    env: node
    plan: free
    buildCommand: npm install && mkdir -p ./.cache/ms-playwright && PLAYWRIGHT_BROWSERS_PATH=./.cache/ms-playwright npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 18484
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.cache/ms-playwright
